git clone https://github.com/yegappan/mru.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/ervandew/supertab.git
git clone https://github.com/vim-syntastic/syntastic.git
git clone https://github.com/godlygeek/tabular.git
git clone https://github.com/majutsushi/tagbar.git
git clone https://github.com/vim-scripts/The-NERD-tree.git
git clone https://github.com/vim-airline/vim-airline.git
git clone https://github.com/altercation/vim-colors-solarized.git
git clone https://github.com/zeis/vim-kolor.git
git clone https://github.com/altercation/vim-colors-solarized.git
git clone https://github.com/easymotion/vim-easymotion.git
git clone https://github.com/tpope/vim-fugitive.git
git clone https://github.com/airblade/vim-gitgutter.git
git clone https://github.com/zeis/vim-kolor.git
git clone https://github.com/tiagofumo/vim-nerdtree-syntax-highlight.git
git clone https://github.com/tpope/vim-repeat.git
git clone https://github.com/tpope/vim-surround.git
git clone https://github.com/tpope/vim-abolish.git
git clone https://github.com/tpope/vim-unimpaired.git
git clone https://github.com/tpope/vim-abolish.git
git clone https://github.com/tpope/vim-commentary.git
git clone https://github.com/honza/vim-snippets.git
git clone https://github.com/MattesGroeger/vim-bookmarks.git 
git clone https://github.com/tmhedberg/matchit.git
git clone https://github.com/Houl/repmo-vim.git
git clone https://github.com/landock/vim-expand-region.git
